### PR TITLE
Add Swift stuffs

### PR DESCRIPTION
**Pull request by devxoul**

### CODE REVIEW

**Comment by KimDarren** [comment]
:+1:

**Comment by darjeeling** [comment]
@devxoul 
I don't have enough experience with Swift and ObjC
do you think those project have enough test-suits and document?
I can't find coverage of tests of those modules.
but I dunno well about UI programming.
how do you think about this?
- Then : doc ok, tests little
- JLToast : doc ok, no tests
- URLNavigator : doc ok, test ok 
- UITextView-Placeholder : doc little, no test
- SwipeBack : doc little, no test
- SSBouncyButton : doc little, no test.

**Comment by devxoul** [comment]
@darjeeling, It'll be better not to add which don't have tests. I just updated the PR :)

**Comment by darjeeling** [comment]
@devxoul Thanks for your understanding.
I just let people do more sustainable open-source with tests, CI and documents

**Comment by devxoul** [comment]
@darjeeling, I definitely agree :+1:

**Pull request merged**
